export class Comuni {

  static comuni = [
    { "nome": "Agrigento", "provincia": "Agrigento", "sigla": "AG" },
    { "nome": "Ancona", "provincia": "Ancona", "sigla": "AN" },
    { "nome": "Arezzo", "provincia": "Arezzo", "sigla": "AR" },
    { "nome": "Ascoli Piceno", "provincia": "Ascoli Piceno", "sigla": "AP" },
    { "nome": "Avellino", "provincia": "Avellino", "sigla": "AV" },
    { "nome": "Bari", "provincia": "Bari", "sigla": "BA" },
    { "nome": "Barletta-Andria-Trani", "provincia": "Barletta-Andria-Trani", "sigla": "BT" },
    { "nome": "Bologna", "provincia": "Bologna", "sigla": "BO" },
    { "nome": "Campobasso", "provincia": "Campobasso", "sigla": "CB" },
    { "nome": "Caserta", "provincia": "Caserta", "sigla": "CE" },
    { "nome": "Catania", "provincia": "Catania", "sigla": "CT" },
    { "nome": "Cagliari", "provincia": "Cagliari", "sigla": "CA" },
    { "nome": "Firenze", "provincia": "Firenze", "sigla": "FI" },
    { "nome": "Ferrara", "provincia": "Ferrara", "sigla": "FE" },
    { "nome": "Fermo", "provincia": "Fermo", "sigla": "FM" },
    { "nome": "Foggia", "provincia": "Foggia", "sigla": "FG" },
    { "nome": "Forlì-Cesena", "provincia": "Forlì-Cesena", "sigla": "FC" },
    { "nome": "Frosinone", "provincia": "Frosinone", "sigla": "FR" },
    { "nome": "Grosseto", "provincia": "Grosseto", "sigla": "GR" },
    { "nome": "Latina", "provincia": "Latina", "sigla": "LT" },
    { "nome": "L’Aquila", "provincia": "L’Aquila", "sigla": "AQ" },
    { "nome": "Livorno", "provincia": "Livorno", "sigla": "LI" },
    { "nome": "Lucca", "provincia": "Lucca", "sigla": "LU" },
    { "nome": "Macerata", "provincia": "Macerata", "sigla": "MC" },
    { "nome": "Massa-Carrara", "provincia": "Massa-Carrara", "sigla": "MS" },
    { "nome": "Matera", "provincia": "Matera", "sigla": "MT" },
    { "nome": "Modena", "provincia": "Modena", "sigla": "MO" },
    { "nome": "Napoli", "provincia": "Napoli", "sigla": "NA" },
    { "nome": "Oristano", "provincia": "Oristano", "sigla": "OR" },
    { "nome": "Perugia", "provincia": "Perugia", "sigla": "PG" },
    { "nome": "Pesaro e Urbino", "provincia": "Pesaro e Urbino", "sigla": "PU" },
    { "nome": "Pescara", "provincia": "Pescara", "sigla": "PE" },
    { "nome": "Pistoia", "provincia": "Pistoia", "sigla": "PT" },
    { "nome": "Pisa", "provincia": "Pisa", "sigla": "PI" },
    { "nome": "Prato", "provincia": "Prato", "sigla": "PO" },
    { "nome": "Ravenna", "provincia": "Ravenna", "sigla": "RA" },
    { "nome": "Reggio di Calabria", "provincia": "Reggio di Calabria", "sigla": "RC" },
    { "nome": "Rieti", "provincia": "Rieti", "sigla": "RI" },
    { "nome": "Rimini", "provincia": "Rimini", "sigla": "RN" },
    { "nome": "Roma", "provincia": "Roma", "sigla": "RM" },
    { "nome": "Salerno", "provincia": "Salerno", "sigla": "SA" },
    { "nome": "Sassari", "provincia": "Sassari", "sigla": "SS" },
    { "nome": "Siena", "provincia": "Siena", "sigla": "SI" },
    { "nome": "Terni", "provincia": "Terni", "sigla": "TR" },
    { "nome": "Trapani", "provincia": "Trapani", "sigla": "TP" },
    { "nome": "Viterbo", "provincia": "Viterbo", "sigla": "VT" }
  ].sort((a, b) => a.nome.localeCompare(b.nome)); // ordine alfabetico per nome

}
